### ISSUE TITLE
Unvisited views causing it to crash

### ISSUE THREAD

**Issue by clem109** [apollographql/apollo-cache-persist#21]
I'm having an issue where on my Home screen, I download a list of for example beers i.e. 
{ id, beerName, beerPrice, beerRating etc }

[online]
Now when I click on the particular item it links to the page containing the data. 

[offline]
If I click on a new item that I haven't previously visited then it causes the application to crash. Whereas links I've previously visited aren't causing it to crash.  So it seems it is only caching the routes I visit.

**Comment by jamesreggio** [comment]
Hi @clem109, could you explain what you expect to happen when you're offline and you tap on an item you haven't previously visited? What do you expect `apollo-cache-persist` to do in that scenario?

**Comment by clem109** [comment]
Well as I have already downloaded the data in the previous request when on the homescreen I expect it to use that data when opening the new view. Something a bit like this: 

https://www.apollographql.com/docs/react/features/cache-updates.html#cacheRedirect

Although I couldn't get that working either. Or am I misunderstanding the purpose of this package?

**Comment by jamesreggio** [comment]
Sorry about the delay, @clem109.

You're correct — the use case you described is something that should be achieved via cache redirects. This package simply persists the data that's in the cache. Somebody may be able to help you through that problem on the [Apollo Slack](https://www.apollographql.com/#slack).

In general, you should try commenting out the call to `persistCache` and make sure everything works as expected. If the bug remains with `persistCache` commented out, the problem is with Apollo Client and not this package.
