### ISSUE TITLE
persistCacheSync not in npm version

### ISSUE THREAD

**Issue by YashGadle** [apollographql/apollo-cache-persist#314]
`persistCacheSync` is mentioned in the documentation but not released on npm.

**Comment by wtrocki** [comment]
CC @benjamn @peggyrayzis

**Comment by wtrocki** [comment]
We have got a response from Apollo, however it can take some time to get access to the package.
Truly recognize the problem and we are working on this.

**Comment by aryzing** [comment]
This issue, or a similar issue informing of the existence of `apollo-cache-persist-dev` should be pinned, or docs updated accordingly: it would really help out. Thanks for mentioning `apollo-cache-persist-dev` here though :)

**Comment by madhums** [comment]
Any update on this? It's quite handy to have this function `persistCacheSync`. Also, seems like a simple fix.

**Comment by darrylyoung** [comment]
> We have got a response from Apollo, however it can take some time to get access to the package.
We are working on this.

Hi, @wtrocki. 👋 

Has there been any update on this? It's been quite a while now and despite the docs explicitly mentioning `apollo-cache-persist-dev`, I've already come across about 3 issues where people are confused that the latest _release_ is `0.2.0` yet that's not even published. I get that there's work to be done and I really appreciate it. It'd be great, if you get chance, if you could give us a little update on this. Are you maybe waiting for Apollo Client 3 to be stable or something? Thanks!

**Comment by wtrocki** [comment]
Since there will be a slight difference in use cases for the Apollo 3.0 we want to probably release separate package - something like `apollo3-cache-persist` and finally finish filtering and direct event-driven store using Apollo 3.0 cache and even more once https://github.com/apollographql/apollo-client/pull/5649 is merged.

There was some info about Apollo 3.0 supporting persistence on its own so that is why over the last 4 months you haven't seen much progress on the repo. Since Apollo 3.0 is now feature complete we can start doing some magic here.

@benjamn @hwillson are you guys ok for the community to start working on cache-persist for apollo3.0? 
Are you planning to include persistence into the client.

**Comment by darrylyoung** [comment]
Thanks for the explanation, @wtrocki. Looking forward to seeing what you can do here. Have a good week!

**Comment by hwillson** [comment]
@wtrocki yes, we are still planning on adding cache persistence to the AC core. It's on the short list of items we're going to look into after AC3 launches. We don't have any timelines to share yet though unfortunately.

**Comment by wtrocki** [comment]
Would this mean that we can collaborate with community and help with bringing offline storage into Apollo-client or you would prefer the core team to deal with this?

There is big offline community around Apollo client that uses Apollo-Cache-persist and similar derivates. What we were struggling with is that we cannot really manage individual objects in the state so, getting something that is embedded into Apollo Cache/Client will be amazing and solve everyone's problems (I hope)

One of the best implementations out there: https://github.com/morrys/wora/tree/master/packages/cache-persist (Done by @morrys) already works with Apollo 3.0

**Comment by markymc** [comment]
Can this be closed now?

**Comment by wtrocki** [comment]
Yes
