### ISSUE TITLE
InMemory cache blocking main thread when loading huge amount of data

### ISSUE THREAD

**Issue by tusharchutani** [apollographql/apollo-cache-persist#415]
I have a component which is loading huge amounts of data (about 19 MB I know probably not the best practice but due to some limitations we have to).

```
const ContextSelector: React.FC = () => {

    const { data, loading } = useQuery<GetLensContext>(GET_LENS_CONTEXT, { variables: { id: "1" } });

    return (
        <div>
            {data && <h1>All loaded</h1>
            </Breadcrumbs>}
            {loading && <CircularProgress />}
        </div>
    )
}
```

The data as I said is about 20 MB and when the data is loading into the CircularProgress and the entire UI is unresponsive. When I set the fetchPolicy to no-cache the UI works as expected and the UI doesn't freeze up. Is there anything I can do to speed this up or make the adding of the data to cache async?

**Comment by wtrocki** [comment]
I have natively stored 50mb of data in apps without no problem using indexedDb. Trick is to save data not as string to avoid JSON.stringify blocking your rendering.

If you have more than 2 mb of data persistence is not the only area to tweak.

For fine tuning this I would recommend to:
1) Save data natively instead of string
2 initialize Apollo client specifically for this component with separate cache persist
3) If you plan to edit and save this stuff set async handler as in readme and longer grace period.

IMHO if you have more than 5mb of data (which is not by confident limit of storage for single row in local storage) you should consider using Delta queries and your own store (or RxDb like solution). While we managed to tweak Apollo stack for large datasets it was always for the price of battery life and huge tradeoffs.
