### ISSUE TITLE
Loading is always true

### ISSUE THREAD

**Issue by iakovosvo** [apollographql/apollo-cache-persist#416]
I am trying to add apollo-cache-persist to my app and I am following the web example (`fetchPolicy: 'cache-and-network`). Loading seems to get stuck at true, even though I can see the data coming back and I get in some sort of infinite loop. Any ideas what is happening here? I can also see this warning in the console:

`Failed to parse source map from '/Users/user/app/node_modules/apollo3-cache-persist/src/storageWrappers/MMKVStorageWrapper.ts' file: Error: ENOENT: no such file or directory,`

**Comment by wodCZ** [comment]
Can you please show your package.json?

The example from master branch seems to be working fine.
![image](https://user-images.githubusercontent.com/1174421/107207489-a4102d80-6a00-11eb-8644-fd7fabf093ee.png)

**Comment by iakovosvo** [comment]
Some of the possible relevant packages:
```
"@apollo/client": "^3.3.6",
"apollo3-cache-persist": "^0.9.0",
"@graphql-codegen/typescript-react-apollo": "^2.2.1",
"@graphql-codegen/add": "^2.0.2",
"@graphql-codegen/cli": "^1.20.0",
"@graphql-codegen/typescript": "^1.20.0",
"@graphql-codegen/typescript-operations": "^1.17.13",
"@graphql-codegen/typescript-react-apollo": "^2.2.1",
"graphql": "^15.4.0",
"react": "~16.14.0",
"source-map-loader": "~1.1.3",
"webpack": "~4.44.2",
"webpack-cli": "3.3.12",
"webpack-dev-middleware": "~3.7.3",
"webpack-dev-server": "~3.11.0"
```

**Comment by wodCZ** [comment]
There's been some work done on examples, but they're not yet released to NPM.
I've created a codesanbox with working web example (based on master, using apollo3-cache-persist 0.9.1): https://codesandbox.io/s/compassionate-heisenberg-rejzl

Previous web example was using somewhat unstable GraphQL API and there was an issue with named exports.
Can you reproduce your issue using the code from the new example and double-check that you're using latest version (`yarn add apollo3-cache-persist`)?

**Comment by iakovosvo** [comment]
I am still getting the same warning. But now I just realised that what makes persistence break is the arguments I have on my query, for searching and pagination  `variables: { token: '', title: '' },` When title is there, it gets in this crazy infinite loop where loading is stuck at true.

**Comment by wodCZ** [comment]
This looks more like apollo cache issue, not related to cache-persist.
I've seen similar behaviour when there were 2 queries on the same page, where the result of one query invalidated (and forced refetch) on the other one.

You can try disabling the persistence by setting `trigger: false` in the cache-persist init. Also, `debug: true` could be handy, but again, I doubt that cache-persist is the source of the issue here. What this package does is basically save the contents of apollo-cache to a persistent storage when the cache changes, and load the last known content from the storage when the app is opened (the loading/restoring part should be done only once during the app initialization if everything is set-up correctly).

**Comment by iakovosvo** [comment]
Thanks for your information, I'll close this now.
