### ISSUE TITLE
Help: How to silently do query in the background?

### ISSUE THREAD

**Issue by kitze** [apollographql/apollo-cache-persist#42]
Hey! 

I've just added this package to my project and it works great. I want to set it up to work this way but I don't know if it's possible:

1. Do initial query
2. The query is persisted into localStorage
3. User closes the app
4. User opens the app again
5. Instead of seeing a loading spinner, the data is loaded from localStorage
6. **But**, the query is still executed in the background, and if data is different, it gets replaced
7. Persist new query again

Is this possible right now? I didn't see any option in the readme.

Thanks!

**Comment by jamesreggio** [comment]
Hi @kitze —

This is pretty much the default behavior you'll get when you use `apollo-cache-persist`. Just be sure to use `fetchPolicy: 'cache-and-network'` with your query to ensure that the cache is hit first *and* the network is also made.

**Comment by kitze** [comment]
@jamesreggio Ok I figured out how to do this .., I struggled a bit because this is not enough:

`
defaultOptions: {
   query: {
        fetchPolicy: 'cache-and-network'
    }
}
`

The `defaultOptions` option is totally ignored unless it includes `query`, `watchQuery`, and `mutation`. Now that that is fixed, there is another problem:

The loading spinner is still displayed because the query is running in the background, although the data is read from the cache. Is there a way to detect this and only display the loading spinner when there is no data in the cache?

Thank you

**Comment by jamesreggio** [comment]
Hmm — that's good to know.

Just for the record, all of these concerns are actually concerns with [Apollo Client](https://github.com/apollographql/apollo-client) and [React Apollo](https://github.com/apollographql/react-apollo), so you may want to consider filing an issue on one of those repos.

You can look at using the `networkStatus` prop instead of the `loading` prop. Here are the various values it may return: https://github.com/apollographql/apollo-client/blob/master/packages/apollo-client/src/core/networkStatus.ts (I can't seem to find the nicely-formatted docs for that option.)

I'm not 100% convinced that you'll find what you need with that prop, either, but here's what you could do (this is what I do in my app to achieve the same effect): instead of using `loading` to control the loading spinner, use `(loading && !data) || networkStatus === NetworkStatus.refetch`. This will basically prevent the spinner from showing upon the initial load if data was immediately returned from the cache, but it will ensure that the spinner shows if the user explicitly requested a refresh (via `refetch`).

Hope this helps.

**Comment by kitze** [comment]
Thank you very much @jamesreggio, that is exactly what I needed!

**Comment by sincospi** [comment]
Checking if data is empty will work, but not in all cases.

A common scenario is that of [`networkStatus === 2` (setVariables)](https://github.com/apollographql/apollo-client/blob/master/packages/apollo-client/src/core/networkStatus.ts)

Consider a query that fetches a list that gets toggled between ASC and DESC.

```
Query-1 (ASC):  loading: true, cache: nil, data: nil
Query-2 (DESC): loading: true, cache: nil, data: yes! (it still holds ASC data)
Query-3 (ASC):  loading: true, cache: yes, data: yes (ASC data from cache)
...
```

So, in this example, `data` is only empty for query-1, but we need to render a loading state for query-1 AND query-2.
Then, on query-3 `data` is filled from the cache, so we no longer need a loading state.

For this scenario, `loading` and `cache` are those that determine if we should render a loading state or not.

```js
(loading && !inCache) ? <Loading /> : <Data />
```

Here is an [implementation that queries the cache](https://github.com/apollographql/react-apollo/issues/1217#issuecomment-567691399).

(Note: the above is only relevant to the `networkPolicy: 'cache-and-network'`)
