### ISSUE TITLE
Cache actually does not persist my data

### ISSUE THREAD

**Issue by duytq94** [apollographql/apollo-cache-persist#45]
Hi all, first thanks for your watching.
I have some issues when use "apollo-cache-persist", hope someone can help.
1. Follow the docs, I know that if I declare these code,
```
const cache = new InMemoryCache({...});
persistCache({
  cache,
  storage: AsyncStorage,
});
const client = new ApolloClient({
  cache,
  ...
});
```
By default, apollo auto persist and restore my data when i query, but in console, it just show
`[apollo-cache-persist] No stored cache to restore` many times although my query is success.

2. Then I try to use CachePersistor instead to handle manually, it persist and restore my data fine, but in my data, it's empty, so I think variable cache when declare at first
 (`const cache = new InMemoryCache({...})`) is the problem, I log this cache and its data always empty although my query is success. Is this variable cache is empty, so CachePersistor can't persist my data?
Any idea or maybe a simple code to demo are good to me.
Thanks a lot!

**Comment by jamesreggio** [comment]
Hi @duytq94 — sorry for the slow response.

I'm going to assume from `storage: AsyncStorage` that you're using this with a React Native app. Let me know if I'm mistaken.

The code you've written above looks correct to me. One problem I've seen before is that developers will initialize two or more instances of `new InMemoryCache()` (or two or more instances of `new ApolloClient`). When this happens, the cache persistor ends up attached to a cache that never contains any data. I'd double-check your code to make sure you're only initializing once (perhaps add a `console.log` statement before each of block of code you pasted above and make sure it only logs once).

If you pass `debug: true` into `persistCache`, `apollo-cache-persist` should log when it goes to persist the cache. You mentioned that it logs that theres 'No stored cache to persist', but does it ever log anything like 'Persisted cache of size XXX' while your app is running? If it does, the problem may lie with AsyncStorage, and not with `apollo-cache-persist`.

My last thought is that you may be using `trigger: 'background'`. If you're using this (which can be helpful for performance on React Native — [more info here](https://github.com/apollographql/apollo-cache-persist#why-is-the-background-trigger-only-available-for-react-native)), you'll need to be sure to send your app to the background to trigger the cache persistence. If you're using the iOS simulator, that means you'll need to press CMD-H to go back to the iOS home screen, and then open your app again, to trigger the cache persistence. If you just press CMD-R to reload your app without doing this, nothing will be persisted, because the app has never gone to the background.

Please let me know if any of this helped — or didn't! — and we can dig deeper.

**Comment by davidalekna** [comment]
I also have this issue, I'm trying to save my data in browsers localStorage but if I debug the output of persistCache I get [apollo-cache-persist] No stored cache to restore... I use apollo-boost to actually configure the apollo,

**Comment by AndreasGalster** [comment]
Hmm ... I have the same issue of the cache not working. I've tried localStorage and sessionStorage so far. The cache actually ends up in the storage but apollo client is not using it ... so in effect the app just fails to retrieve the cached data and everything fails.

**Comment by lokey** [comment]
@duytq94 I had a similar issue where log says  'Persisted cache of size 2'. But nothing is actually persisted. It seems to be caused by importing ApolloClient from `apollo-boost`. I fixed it by changing my import to `import { ApolloClient } from 'apollo-client';`

**Comment by duytq94** [comment]
Thanks @lokey I'll check it again.

**Comment by wtrocki** [comment]
@duytq94 Since Apollo boost is out of the way this issue may no longer be relevant.
Can you confirm?
