### ISSUE TITLE
React Native | Network Request Error

### ISSUE THREAD

**Issue by tamangsuresh** [apollographql/apollo-cache-persist#453]
**Happenings:**
Persist work fine but when I use app too much and turn off my network along with restart app. It shows persist restored cache message but in UI, there is network request error. Any thing I'm missing.
**Expected:**
App should work even when there is no network after using it too much.

<img width="335" alt="Screen Shot 2021-10-29 at 11 25 29 AM" src="https://user-images.githubusercontent.com/21368268/139381807-3785d339-3fb4-4505-bff7-51d16f2f433c.png">
<img width="689" alt="Screen Shot 2021-10-29 at 11 26 00 AM" src="https://user-images.githubusercontent.com/21368268/139381867-7a9ce774-20bd-4220-817b-1baa063bfb1a.png">
<img width="537" alt="Screen Shot 2021-10-29 at 11 31 38 AM" src="https://user-images.githubusercontent.com/21368268/139384084-da3090f6-35ef-4066-8292-a355d713861f.png">
<img width="752" alt="Screen Shot 2021-10-29 at 11 59 01 AM" src="https://user-images.githubusercontent.com/21368268/139384898-d85fe189-431a-430d-a91b-8ece97d4623d.png">

**Comment by wodCZ** [comment]
I believe the `cache-and-network` fetch policy could be the issue here. It'll depend on how you're rendering the content. E.g. if you're first checking for the `error` and only render the data if `error` is undefined, you probably will see the error message even though there is some `data` in cache.

In other words the `-and-network` failed, which, I believe, gets in your `error` variable, but in `data` you probably still have the cached/restored response.

If you're still having this issue, feel free to comment with [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and I'll reopen the issue.
