### ISSUE TITLE
Warning after upgrading to React Scripts (CRA) 5.0.0

### ISSUE THREAD

**Issue by cesargdm** [apollographql/apollo-cache-persist#455]
Just after upgrading to CRA v5 the development server logs this error several times:

```bash
WARNING in ./node_modules/apollo3-cache-persist/lib/storageWrappers/LocalForageWrapper.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '{{PATH}}/node_modules/apollo3-cache-persist/src/storageWrappers/LocalForageWrapper.ts' file: Error: ENOENT: no such file or directory, open '{{PATH}}/node_modules/apollo3-cache-persist/src/storageWrappers/LocalForageWrapper.ts'
 @ ./node_modules/apollo3-cache-persist/lib/storageWrappers/index.js 3:0-37 3:0-37
 @ ./node_modules/apollo3-cache-persist/lib/index.js 4:0-40 4:0-40
 @ ./src/App.tsx 13:0-53 46:4-16
 @ ./src/index.tsx 18:0-24 46:36-39
 ```

- [x] Using LocalForage

**Comment by kiano0sh** [comment]
Having the same issue.

**Comment by cahilfoley** [comment]
I'm having the same issue as well. This seems to be because TypeScript is configured to generate source maps that point back to the original source files:

https://github.com/apollographql/apollo-cache-persist/blob/0ace201137a793212eb8f58fecf62df3efc0d1ab/tsconfig.json#L12

But the npm package is ignoring them when publishing:

https://github.com/apollographql/apollo-cache-persist/blob/0ace201137a793212eb8f58fecf62df3efc0d1ab/.npmignore#L1

I'm sure there are a number of ways to resolve the issue but some suggestions that spring to mind would be any of the following:
- Disable source map generation altogether; or
- Publish the source files alongside the generated code; or
- ~Ignore the source map files when publishing the package~ *The source map URLs would still exist in the generated JS files so this wouldn't resolve the problem*

**Comment by tutok** [comment]
I believe there are two options:
* there should not be source maps - source maps should not be generated at all, or should not be deployed
* or, sources should be delivered together with source maps ( sources can be inlined https://www.typescriptlang.org/tsconfig#inlineSources)
