### ISSUE TITLE
Is it possible not to persist data to storage if it's undefined ? 

### ISSUE THREAD

**Issue by VasRoko** [apollographql/apollo-cache-persist#513]
I need a bit of help; I'm not sure if it's intended behavior or a bug where empty data in persistenceMapper function is stored in localStorage as `undefined` which results in entire cache being cleared. 

**Use case:** 
I have `cacheContents`, which are typically products fetched from the server and stored in the cache. Next, I would like to pull out `tempContents` that are stored in localStorage, combine them with `cacheContents`, and store all in the Apollo cache. However, I want to keep only `tempContents` in localStorage not `cacheContents`.

It seems that this is possible to achieve with the usage of `persistenceMapper` where I can define what I want to store in my localStorage. This works as expected when some data is already in localStorage; however, the issue arises when the user loads the page for the first time, and `tempContents` do not exist. Therefore, filtered data is set to undefined. The problem with undefined it completely wipes out everything in my cache, so the page is empty.

**Code Example**   

```
  const productResponse= await apolloClient.query({
    query:  SHOP_QUERY,
    variables: { shopId: shopId },
    fetchPolicy: 'no-cache' // Not stored in cache, so we can transform it
  });

  const cacheContents = transformToCacheState({
    ...productResponse.data.products,
  }); <=== additional processing logic 

  await persistCache({
      cache: cache.restore(cacheContents), 
      storage: new LocalStorageWrapper(window.localStorage),
      debug: true,
      persistenceMapper: async (data: any) => {  
        const parsedData = JSON.parse(data);  // mapper to persist only temp items
        const filteredData = JSON.stringify(parsedData['ROOT_QUERY']['tempItems']);  <======= this is empty on initial loads
        return filteredData; <=======  sets localStorage to `undefined` and wipes out all cache contents . 
      }
  });
  cache.writeQuery({
    query: SHOP_QUERY,
    data: { shopId }
  });
```

Is there a way solve this?

**Comment by wodCZ** [comment]
Hi @VasRoko!

The code using `persistenceMapper` option is on single place, which is here:
https://github.com/apollographql/apollo-cache-persist/blob/cbf1b191b3f37eafe8d95fa0c557957f86f5a909/src/Persistor.ts#L41-L75

As you can see, it's called with whatever the cache content is, and the returned value gets persisted. If you return undefined, the undefined gets persisted.
I believe the behaviour you're illustrating is expected in this case, although I didn't fully get what you're trying to achieve (fault is on my side, late evening).

Maybe following this test case:
https://github.com/apollographql/apollo-cache-persist/blob/cbf1b191b3f37eafe8d95fa0c557957f86f5a909/src/__tests__/persistCache.ts#L177-L182
You could return _something_ as a initial state instead of undefined?

Also, I'd suggest taking a break (I'd need one too 😅). From the looks of it, you're juggling with caches on several layers (in-memory & persisted) which *will* be difficult to keep in sync.
It feels like your use-case is just around the line where apollo and cache-persist's capabilities end, i.e. a full-featured state management system would be a better option, than trying to mutate apollo's _internal_ cache.

**Comment by wodCZ** [comment]
> it won't be possible (or at least not easily) to combine in-memory & persisted but only store some parts of Apollo in local storage

There's https://github.com/TallerWebSolutions/apollo-cache-instorage, a result of discussion in https://github.com/apollographql/apollo-cache-persist/issues/2#issuecomment-350823835.
Also, we had a custom persistence mapper example [here](https://github.com/apollographql/apollo-cache-persist/blob/6319832025b87fae235c06c1257f9d59c65fc239/examples/react-native/src/utils/persistence/README.md) (and [here](https://github.com/apollographql/apollo-cache-persist/blob/6319832025b87fae235c06c1257f9d59c65fc239/examples/react-native/src/utils/persistence/persistenceMapper.ts)). Maybe that would help you?


> mutating apollo cache, has in some sense functioned as a state management system

Yeah, I've been there. I didn't mean to attack your decision, my suggestion was purely a friendly advice. I guess I'm biased against storing an app state next to a http layer.
