### ISSUE TITLE
Whitelist GQL requests

### ISSUE THREAD

**Issue by oliver-jenny** [apollographql/apollo-cache-persist#531]
Hey! 👋

We have 3 fairly large requests in our application and would like to cache them permanently.

After setting up appollo3-cache-persist we encountered the problem that everything in our cache is now permanent. For some cases, such as the user's session, this is very inconvenient in our case.

Hence the following question: is it possible to implement a "custom persistor" with the CachePersistor, which filters by key-value pairs or is there already a filter/whitelist function hidden somewhere?

Thanks in advance for the answer

Regards,
Oli

**Comment by wodCZ** [comment]
Hi Oli,

that would be a job for custom `persistenceMapper`. Please have a look at this issue: https://github.com/apollographql/apollo-cache-persist/issues/513 where I've linked some relevant resources.

We had an example of such `persistenceMapper` in this repo, but I removed it since it was a little complex and confusing, but the functionality is still supported and should allow you to build an allowlist of persist-able queries
- [Readme](https://github.com/apollographql/apollo-cache-persist/blob/6319832025b87fae235c06c1257f9d59c65fc239/examples/react-native/src/utils/persistence/README.md)
- [persistenceMapper](https://github.com/apollographql/apollo-cache-persist/blob/6319832025b87fae235c06c1257f9d59c65fc239/examples/react-native/src/utils/persistence/persistenceMapper.ts)

Both are mentioned in the linked issue, just a bit hidden.

Also, using correct fetch policy is important, see [apollo docs](https://www.apollographql.com/docs/react/data/queries/#setting-a-fetch-policy). `cache-and-network` would be a good choice for user content that could be stale for a moment but needs to be re-fetched.

Hope this helps,
Martin

**Comment by oliver-jenny** [comment]
Hey Martin

That's also the solution I came up with, sorry I forgot to close the issue :)
Thanks for answering tho 👍 

Oli
