### ISSUE TITLE
Cleaner React implementation suggestion

### ISSUE THREAD

**Issue by ivank** [apollographql/apollo-cache-persist#59]
Hi guys I wanted to talk a bit about https://github.com/apollographql/apollo-cache-persist#how-do-i-wait-for-the-cache-to-be-restored-before-rendering-my-app as this seems to be a common problem. 

The solution looks straight forward, but not very elegant. I was thinking that we could use a "render props component" in the style of the new `<Query />` and `<Mutation />` components to make this more elegant. In fact, I've created such a component for my own needs - https://github.com/ovotech/async-reactor-ts though its a bit more generic than that.

I was thinking that I could write a PR with something like this but more specific to apollo, so it has a nicer interface, but don't know where such a component will go, since `apollo-cache-persist` does not know about React.

**Comment by wtrocki** [comment]
> I was thinking that I could write a PR with something like this but more specific to Apollo, so it has a nicer interface, but don't know where such a component will go, since apollo-cache-persist does not know about React.

I think that will be the main problem. Apollo-cache-persist does a really good job on the separation of concerns now and offers promise so users are getting a possible way to restore cache before attaching a client to React provider or do it later.

With that in mind I think that since there is possibility in actual library some external library can be used to provide components for desired framework. 

@ivank if you have anything that could be lets say added to docs as improvement for react developers please givie us shout. Closing for the moment
