### ISSUE TITLE
Option to synchronously restore cache

### ISSUE THREAD

**Issue by bennypowers** [apollographql/apollo-cache-persist#61]
Can there be an option for `persistCache` to work synchronously? For users that are using localStorage or sessionStorage, it would be nice to run `persistCache` to completion before instantiating the client, and export the client as a direct value, instead of a Promise.

**Comment by n1ru4l** [comment]
I think https://github.com/apollographql/apollo-cache-persist/issues/59 would be a better way to tackle this.

**Comment by bennypowers** [comment]
Thanks for the tip, @n1ru4l, but I'm not using React, I'm using [`lit-apollo`](https://github.com/bennypowers/lit-apollo), so solutions that rely on React-specific APIs are less relevant to my use case.

**Comment by wtrocki** [comment]
From my experience with the framework that uses cache persist very often having synchronous api (as the separate method will significantly degrade the performance of the UI. Cache can go to 10mb and more so async API is just recommended.

@bennypowers I checked current code and It will be hard for us to maintain generic solution and support synchronous api, the however codebase is quite small so you can adapt it for your own needs and create synchronous persistor.

**Comment by andrewshirk** [comment]
> From my experience with the framework that uses cache persist very often having synchronous api (as the separate method will significantly degrade the performance of the UI. Cache can go to 10mb and more so async API is just recommended.
> 
> @bennypowers I checked current code and It will be hard for us to maintain generic solution and support synchronous api, the however codebase is quite small so you can adapt it for your own needs and create synchronous persistor.

@wtrocki Would you mind explaining why it would hard to maintain a synchronous version? It seems like all would need to do is to add an alternative, synchronous version of the restore() method. Thank you.

**Comment by wtrocki** [comment]
@andrewshirk Any contribution is welcome. My concern was purely on correctness. 
If someone passes async store to persistor (both LocalForage and React store are async) then how restore would behave. However if we document that there should not be any problem to get alternative version. Would you have time to contribute - I will take look and integrate your change assuming that it will not affect current API and it will jus provide alternative restore method.

**Comment by wtrocki** [comment]
Generally speaking, I would need to provide context of why this change wasn't done before and how we can do it to make sense.  So long story short I was reluctant to do it because of numerous reasons:

- Using sync api is generally and bad idea here as it will slow down entire UI (depending on the cache size) without the ability to provide progress bar or Launcher view. 
- Our current interface allows both async or sync api which means that I was thinking be hard to make a proper change here without making internals messy
- Generally, it is really easy to make async api and synchronous by awaiting it - even on global scope (https://v8.dev/features/top-level-await) 
- Initially, we had no way to release breaking changes that will not affect entire community.

However, I was talking with a couple devs that also had local storage implemented and:

- For the purpose of the sample apps, examples or small apps that will never go above 20kb cache sync store is still the best option. For such use cases, progress bar is overkill
- Having a single interface that supports both sync and async is kinda bad api.
- There is easy way to make non breaking change by having 3 variations of persitors and 3 storage interfaces (later 2 interfaces after depreciation of the current one)

Really like your suggestions. From my side is best if someone creates simple PR with idea as I can review and possibly extend it (another pair of eyes really helps)
A separate Persistor instance will be awesome. If we can do `persistCacheSync` as helper it will be even better.

**Comment by andrewshirk** [comment]
@wtrocki Thank you for your explanation. Your reluctance is understandable, and I think the reasons are justified. That said, my proposal would at least provide devs a stop gap until they can redesign their code to accommodate the async API. My use case is exactly as you describe—an app with very small localStorage requirements.

Below is my implementation. This is functioning code, and seems to do the trick for my employer. It does what I needed it to do without affecting any of the existing API. I will submit a pull request. Please let me know your thoughts. If you'd like, I can implement a version in TypeScript.

```js
import { CachePersistor } from 'apollo-cache-persist';
import Persistor from 'apollo-cache-persist/Persistor';
import Storage from 'apollo-cache-persist/Storage';

export default function(options) {
  const cachePersistor = new SynchronousCachePersistor(options);
  cachePersistor.syncRestore();
}

class SynchronousCachePersistor extends CachePersistor {
  constructor(options) {
    super(options);

    this.storage = new SynchronousStorage(options);
    this.persistor = new SynchronousPersistor(
      { log: this.log, cache: this.cache, storage: this.storage },
      options,
    );
  }

  syncRestore() {
    this.persistor.syncRestore();
  }
}

class SynchronousPersistor extends Persistor {
  constructor({ log, cache, storage }, options) {
    super({ log, cache, storage }, options);
  }

  syncRestore() {
    this.cache.restore(this.storage.syncRead());
  }
}

class SynchronousStorage extends Storage {
  constructor(options) {
    if (
      options.storage !== window.localStorage &&
      options.storage !== window.sessionStorage
    ) {
      new Error(
        'SynchronousStorage supports only synchronous storage providers (winodw.localStorage and window.sessionStorage).',
      );
    }
    super(options);
  }

  syncRead() {
    return this.storage.getItem(this.key);
  }
}
```

Then, just import, and call:

```js
import syncPersistCache from './syncPersistCache'

syncPersistCache({
    cache: cache,
    storage: window.localStorage,
})
```

**Comment by wtrocki** [comment]
Thanks to awesome work of the @andrewshirk this feature is now enabled in `apollo-cache-persist-dev` package. Hoping to release official 0.2.0 in comming weeks :)

Social: https://twitter.com/wojtroken/status/1187292150456868865
