### ISSUE TITLE
Persisted cache keeps on growing with each refresh

### ISSUE THREAD

**Issue by gabriel-dehan** [apollographql/apollo-cache-persist#69]
Hello,

I am pretty new to the GraphQL/Apollo thingy in general and I am having issues with the caching of the result of a query I am making. 
The query takes a datetime as an argument and returns a bunch of statistics - whatever.
When the result is stored in the localStorage it looks like that: `$ROOT_QUERY.statistics({"datetime":"2018-09-25T04:22:49.635Z"}):...`

As you can see it is stored with the argument in the key which makes it creates a new one everytime I do a page refresh.

In the end I get something like this and my local storage quickly hits the limit.
<img width="649" alt="screen shot 2018-09-25 at 15 27 53" src="https://user-images.githubusercontent.com/1383633/46017400-ab586a00-c0d7-11e8-8543-d41eb7625ad7.png">

It feels like there are multiple ways of going around this, but I wanted to understand the best practices and why it stored the arguments in the quey. Why not just leave it at `$ROOT_QUERY.statistics`? What are the proper ways of handling these kind of behaviours? Not sure if this is a common issue or something very specific here.

Thanks and cheers :pray:

**Comment by pl12133** [comment]
I think this is a symptom of the lack of a cache invalidation strategy, and right now you will have to deal with cache invalidation yourself since `apollo-client` doesn't have a built-in invalidation strategy.

A very naive cache invalidation strategy would be calling `client.resetStore()` to clear the cache and refetch all watched queries.

Please see the main issue tracking cache invalidation: https://github.com/apollographql/apollo-feature-requests/issues/4

**Comment by jamesreggio** [comment]
Yep, @pl12133 is correct — there's no way to selectively remove/overwrite these.

The only other suggestion is to set a sensible `maxSize` option and let `apollo-cache-persist` automatically reset itself periodically.

**Comment by SnidelyWhiplash** [comment]
@gabriel-dehan I know this is a bit old (and closed) but I actually think you can use the [@connection directive](https://www.apollographql.com/docs/react/features/pagination.html#connection-directive) for this to specify the cache key.
